#!/bin/bash
#
# Perform GitHub publish
if [ -z "$PUBLISHER_LOGIN" ]
then
  echo "Environment variable PUBLISHER_LOGIN must be set"
  exit 1
fi

if [ -z "$PUBLISHER_PASSWORD" ]
then
  echo "Environment variable PUBLISHER_PASSWORD must be set"
  exit 1
fi

MODULES_ROOT=`pwd`
cd $(dirname $0)
set -o pipefail
mvn -s settings.xml -Dforge.modules.root="$MODULES_ROOT" -Dmaven.skip.install deploy | egrep --color=never "(^\[WARNING\]|^\[ERROR\])"

